[tool.poetry]
name = "hexlet-code"
version = "0.1.2"
description = ""
authors = ["Anton Tyurin <AntonTyurin87@gmail.com>"]
readme = "README.md"
packages = [{include = "hexlet_code"}]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
gendiff = "scripts.gendiff:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
